---
bind_blackhole_malwaredomain_blocklist_url: 'http://mirror2.malwaredomains.com/files/justdomains'
bind_dns_fqdn_name: dns1.home
bind_hostmaster_name: hostmaster.home
bind_acls: 
  goodclients:
    values: ['172.16.0.0/16' ,'127.0.0.1','10.0.0.0/8','192.168.0.0/16']
bind_options_allow_recursion: ['goodclients']
bind_options_allow_query: ['goodclients']
bind_options_additionals:
  - 'response-policy { zone "rzp-static-dhcp"; }'
bind_options_forwarders: ['10.138.89.100','10.138.89.101']
bind_logging_channels:
   default:
     out: syslog daemon
     severity: info
   update_log:
     severity: "debug 3"
     file: "logs/update.log"
     print_time: yes
     print_category: yes
     print_severity: yes
bind_logging_categories:
   default:
     values: [ 'default']
   update:
     values: [ 'update_log' ]
bind_keys:
  ddns-key:
    algorithm: 'hmac-md5'
    secret: 'cRweA+41mHv+aVcv2ZDI4A=='
bind_zones:
   zone_home_dhcp:
     name: 'home.dhcp'
     type: master
     dynamic: true
     managed: false
     parameters:
       - 'allow-update { key "ddns-key"; }'
   zone_home:
     name: 'home'
     type: master
     managed: true
     content: "{{ zone_home }}"
   zone_172_31_1_rev:
     name: "1.31.172.in-addr.arpa"
     type: master
     managed: true
     content: "{{ zone_172_31_1_rev }}"
   zone_172_31_1_static_rev:
     name: "static.1.31.172.in-addr.arpa"
     type: master
     managed: true
     content: "{{ zone_172_31_1_static_rev }}"
   zone_172_31_1_dhcp_rev:
     name: "dhcp.1.31.172.in-addr.arpa"
     type: master
     managed: false
     dynamic: true
     parameters:
       - 'allow-update { key "ddns-key"; }'
   zone_rzp_static_dhcp:
     name: "rzp-static-dhcp"
     type: master
     managed: true
     dynamic: false
     content: "{{ zone_rzp_static_dhcp }}"
     parameters:
       - 'allow-query { none; }'
